### PR TITLE
Update beginners.cpp

### PR DESCRIPTION
**Pull request by SathyaseelanRamachandran**
I have modified the line code to enhance the code performance in question number 1

### CODE REVIEW

**Comment by Tomyzon1728** [comment]
Good job Sathy

**Comment by SathyaseelanRamachandran** [comment]
Noted and thank you.

**Comment by SathyaseelanRamachandran** [comment]
I will modify and make alteration in the code. Will pull a request to be verify by you sir

**Comment by Tomyzon1728** [comment]
Ok ,I'll be looking forward to that .

**Review by Tomyzon1728 — APPROVED** [review]
You've done an awesome job . The changes were long overdue . Well-done

**Comment by SathyaseelanRamachandran** [comment]
is there any other GUI that you were looking for in the program sir?

**Comment by SathyaseelanRamachandran** [comment]
int prueba(int x, int y)
{
  rectangle(x,y,x+70,y+20);
  
  if(mousex()>x && mousex()<x+70 && mousey()>y && mousey()<y+20 && ismouseclick(WM_LBUTTONDOWN))
    {   
	    clearmouseclick(WM_LBUTTONDOWN);
    	return 1;
	}
  else
    {
    	clearmouseclick(WM_LBUTTONDOWN);
  	    return 0;
    }     
}

//this might be useful to create button click

**Comment by Tomyzon1728** [comment]
Not for now but in the future , Definitely

**Comment by Tomyzon1728** [comment]
Good job Sathy ,your contributions so far have been really helpful

**Pull request merged**
